Update to OmniPay 3.0
elvanto/omnipay-tithely pull request #1
Opened 2019-08-29 02:59 UTC by StewPoll

This PR updates the library to allow it to be used in Omnipay 3.0

**Code Review:**
- [ ] Unit tests exist
- [ ] Code formatting standards reviewed (PSR-2, DocBlocks, whitespace)

2019-08-29 03:51 UTC, joshmcrae requested changes
Tests are failing on Travis due to PHP version. Since 5.6 is the lowest supported, versions below this should be removed from the build.

2019-08-29 03:51 UTC, joshmcrae commented on src/Message/AbstractRequest.php
> +                    ['auth' => [$this->getPublicKey(), $this->getPrivateKey()]],
The API documentation doesn't indicate that the authentication details can go into the request payload.

Could you please explain the reason for this change?

https://docs.tithe.ly/reference#charge-object

2019-08-29 03:51 UTC, joshmcrae commented on src/Message/AbstractRequest.php
> +                'auth' => [$this->getPublicKey(), $this->getPrivateKey()]
As above.

2019-08-30 00:11 UTC, StewPoll commented
@joshmcrae 
After looking at the docs, and how a few other similar plugins are doing it, I can see no reason for this.

I've made some changes on behalf of Ryan.

2019-08-30 02:36 UTC, joshmcrae requested changes
There are still failing tests. I've updated the Travis CI configuration to include only the relevant PHP versions.

There appears to be a compatibility issue with PHPUnit.

2019-09-03 00:59 UTC, joshmcrae approved these changes

2019-09-04 05:15 UTC, merged